In [69]:
import numpy as np

In [70]:
np.unique([2,5,2,3,7,9])

array([2, 3, 5, 7, 9])

In [71]:
arr = np.random.randint(5, 25, 10)
arr

array([10,  5, 19, 22,  9, 18,  9,  7,  6,  7])

In [72]:
arr.ndim

1

In [73]:
np.array([1,2,3,4,5], ndmin=2)

array([[1, 2, 3, 4, 5]])

In [74]:
arr

array([10,  5, 19, 22,  9, 18,  9,  7,  6,  7])

In [75]:
arr[::2]

array([10, 19,  9,  9,  6])

In [76]:
arr[0:5:2]

array([10, 19,  9])

In [77]:
np.unique(arr, return_inverse=True)

(array([ 5,  6,  7,  9, 10, 18, 19, 22]),
 array([4, 0, 6, 7, 3, 5, 3, 2, 1, 2]))

In [78]:
data = np.random.randint(2,15, (5,3))
data

array([[ 5, 13, 13],
       [14,  3,  3],
       [11,  8,  8],
       [ 4, 13,  2],
       [ 6, 13, 12]])

In [79]:
np.sum(data, axis=0)

array([40, 50, 38])

In [80]:
np.sum(data, axis=1)

array([31, 20, 27, 19, 31])

In [81]:
np.max(np.sum(data, axis=1))

31

In [82]:
np.max(np.sum(data, axis=0))

50

In [83]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.full((2,5), 69)

array([[69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69]])

In [85]:
gg = np.random.randint(2,10, (4,6))
print(gg)
print(gg.shape)

[[4 2 8 6 3 5]
 [5 5 3 9 8 3]
 [2 2 9 8 6 5]
 [8 9 3 9 8 2]]
(4, 6)


In [86]:
ft1 = gg.flatten()
print(ft1)
print(ft1.shape)

[4 2 8 6 3 5 5 5 3 9 8 3 2 2 9 8 6 5 8 9 3 9 8 2]
(24,)


In [87]:
ft2 = gg.reshape(24)
print(ft2)
print(ft2.shape)

[4 2 8 6 3 5 5 5 3 9 8 3 2 2 9 8 6 5 8 9 3 9 8 2]
(24,)


In [88]:
ft1 == ft2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [89]:
ft3 = gg.reshape(-1)
ft3.shape

(24,)

In [90]:
ft1 == ft3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [91]:
ft4 = gg.reshape(24)
ft4.shape

(24,)

In [92]:
ft1 == ft4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [93]:
arr2d = np.random.randint(2,10, (5,4))
arr2d

array([[4, 7, 2, 9],
       [3, 3, 2, 3],
       [7, 2, 3, 2],
       [4, 6, 2, 9],
       [4, 6, 5, 9]])

In [94]:
reshaped = arr2d.reshape(2,5,2)
reshaped.shape

(2, 5, 2)

In [95]:
reshaped.ndim

3

In [96]:
reshaped

array([[[4, 7],
        [2, 9],
        [3, 3],
        [2, 3],
        [7, 2]],

       [[3, 2],
        [4, 6],
        [2, 9],
        [4, 6],
        [5, 9]]])

In [100]:
arr_temp = np.random.randint(15,25,(8,6))

In [101]:
arr_temp.shape

(8, 6)

In [105]:
arr_temp[arr_temp[:, 1] > 5, 1]

array([17, 16, 17, 19, 23, 19, 22, 20])

In [106]:
arr_temp[:, 1][arr_temp[:, 1] > 5]

array([17, 16, 17, 19, 23, 19, 22, 20])

AttributeError: module 'numpy' has no attribute 'Series'