In [3]:
import numpy as np

#Heights of the players is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it ?


1.   create an random integer numpy array for heights in inches in the range 67 to 83 of size 1015

2.   create an random integer numpy array for wights in lbs in the range 150 to 290 of size 1015





In [5]:
height_in = np.random.randint(67,83,1015)
weights_lb = np.random.randint(150, 290, 1015)

# Convert the heights from inches to meters
heights * 0.0254

In [12]:
heights = height_in * 0.0254
heights

array([1.8542, 2.0828, 1.7526, ..., 2.0828, 1.7018, 2.0066])

# Converting weights in lbs to kg =weights_lb * 0.453592

In [13]:
weights = weights_lb * 0.453592
weights

array([ 76.203456,  98.883056,  73.935496, ..., 101.151016,  92.079176,
        98.883056])

# Calculate the BMI: bmi

In [14]:
bmi = weights / heights ** 2
bmi

array([22.1646825 , 22.7943253 , 24.0706255 , ..., 23.31713093,
       31.79394258, 24.55841105])

Fetch the first element from the bmi array

In [ ]:
bmi[0]

Fetch the first element from the bmi array

Fetch the first five element from the bmi array

In [15]:
bmi[:5]

array([22.1646825 , 22.7943253 , 24.0706255 , 28.82572209, 23.31922517])

Count the number of pariticipants who are underweight i.e. bmi < 21

Players list contain the height(inches) and weight(lbs) data for all the players

In [17]:
bmi[bmi < 21]

array([20.51457886, 16.72978004, 18.50731917, 19.71904068, 17.78836382,
       20.54279752, 20.54279752, 19.47559574, 20.89596955, 18.7452609 ,
       18.49869539, 17.77539129, 18.02452187, 20.79933875, 20.80085817,
       20.44937552, 20.15738385, 19.18301365, 17.90628875, 19.13468592,
       19.52969461, 18.74850683, 19.93962732, 20.2848583 , 18.71644142,
       19.32876505, 19.55293042, 20.20593058, 20.15738385, 18.45556141,
       19.18301365, 20.69282047, 19.50290491, 16.62521891, 17.46125556,
       16.07382273, 18.64563436, 17.67083017, 17.79628977, 20.34343189,
       18.38009348, 19.61006373, 20.91222505, 16.10241329, 20.34343189,
       15.68416879, 18.00268146, 18.72077235, 19.78989509, 20.05376036,
       20.038699  , 18.61727677, 20.18569299, 18.74850683, 18.02452187,
       19.48901427, 17.25258567, 20.02899287, 19.82438136, 20.75030053,
       19.21018367, 20.72820015, 18.53847555, 19.25864699, 20.71342352,
       19.55410673, 20.61554689, 20.59854167, 18.38009348, 19.68

In [20]:
tmp = np.arange(5, 55, 3)
tmp

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53])

In [21]:
np.min(tmp)

5

In [22]:
np.max(tmp)

53

In [24]:
tmp[np.argmax(tmp)]

53

In [25]:
np.argmin(tmp)

0

In [27]:
singledarray = np.arange(2,50,3)
singledarray

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [30]:
singledarray.size

16

In [32]:
singledarray.reshape(2,-1)

array([[ 2,  5,  8, 11, 14, 17, 20, 23],
       [26, 29, 32, 35, 38, 41, 44, 47]])