# Exercise Background

This small application based coding exercise is ment to expose you to the use of the numpy library as well as give you a taste of tasks that you might be needed to perform during machine learning. 

Usually, machine learning involves working on large data sets. This notebook will walk you through normalising the data and then dividing the data set into smaller subsets. It is recommended that while attempting each of the tasks visit the NumPy library to find the most appropriate function which can help you achieve the desired result. More often than not you will find the functions which you require prewritten in the library. The **numpy library** can be found [here.](https://numpy.org/doc/stable/) 

Without further ado, the first task is to mean normalise a data set. Mean normalising is a data transformation done to reduce the variations in the data set. For example, consider a data set which has integers between 0 and 10000. That is a lot of variation, and it becomes difficult to build ML algorithms on this data. So mean normalisation is done on such data, after the transformation, the mean of the data will be zero, and standard deviation will be 1.  Even though the actual values of data will change a lot, but the overall variation is still kept intact. If the concept of normalisation feels a bit unclear dont worry all of this will be covered in the future sections of this program. For now, let’s concentrate on the tasks at hand. 


# Task 1: Mean Normalisation: 

**Question 1.1** Create a 2D of random integers between 0 and 10,000 (including both 0 and 10,000) with 25000 rows and 15 columns. This will be the dataset you will use in the notebook. 

In [13]:
# import NumPy into Python
import numpy as np

# Create a 25000 x 15 ndarray with random integers in the interval [0, 10000].
X = np.random.randint(10000, size=(25000, 15))

# print the shape of X
X.shape

(25000, 15)

In [14]:
# print the first row of X
X[0]

array([5254, 2276, 2195, 9644, 7907, 2115, 7940, 4789, 2945, 3911, 2771,
       4412, 1245, 5524, 3032])

Now that you created the array we will mean normalize it. The equation for normalisaing the data is given below:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. To put it simply, to find the new value of each element, you have to subtract the mean of respective column form that value and divide the result with the standard deviation of that columns. Now the question is, Why are these operations being done column-wise? That is because usually all the procedures in ML are done column-wise. So it will be beneficial for us to develop the habit of thinking about data column-wise.   

**Question 1.2** Find the mean and the standard deviation of each of the columns in the dataset. The result will be two 1D arrays with 15 elements each, representing the mean and standard deviation for each of the columns in the dataset.  

In [22]:
# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# print ave_cols  
print(ave_cols)
print(ave_cols.shape)

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)

# print std_cols  
print(std_cols)
print(std_cols.shape)


[4997.3014  5015.6788  4988.6064  4984.38284 5020.6146  4971.40464
 4990.1032  4995.3326  4993.70312 4996.78076 4992.56344 4996.92124
 5008.23436 5000.2674  4970.85804]
(15,)
[2888.15241069 2887.27867141 2891.66818176 2878.43877976 2890.51184395
 2884.66384034 2872.86287377 2873.18773947 2880.37809871 2885.6634407
 2892.3381827  2887.71971282 2888.82506771 2883.1976336  2872.93399232]
(15,)


**Question 1.3** Print the shape of each both the arrays, they should have 15 elements each.  

In [23]:
# Print the shape of ave_cols
ave_cols.shape

# Print the shape of std_cols
std_cols.shape

(15,)

**Question 1.4** Now that you have mean and standard deviation calculated, it is time to apply the transformation to the dataset. 


In [26]:
# Mean normalize X
x_norm = (X-ave_cols)/std_cols
x_norm

array([[ 0.08887987, -0.94887924, -0.96608816, ..., -1.30268683,
         0.18164991, -0.67487037],
       [ 1.02581103,  0.68414636,  1.16555337, ...,  0.02207321,
        -1.13320966,  0.07210119],
       [ 0.47944097,  1.27155069,  0.86226823, ..., -1.69177235,
         1.52321594, -0.96098903],
       ...,
       [ 0.91882222, -0.9204788 , -0.59156386, ..., -0.5369776 ,
         1.05706684,  0.32654491],
       [ 0.65983311,  1.43987529,  0.10526574, ...,  0.79782112,
         0.47680831,  1.32204289],
       [-1.65341046,  0.56292495,  0.42895433, ...,  0.85355312,
        -0.80267387, -1.61746077]])

**Question 1.5** If the transformation has been performed correctly, the mean of elements in each column will be approximately 0. Also, the average of the **minimum** value in each column of X_norm and the average of the **maximum** value in each column of X_norm will have almost the same face value with opposite signs. Let’s confirm if the transformation has happened correctly. 

In [29]:
# Print the average of all the values of X_norm
np.mean(x_norm)

# Print the average of the minimum value in each column of X_norm
np.mean(np.min(x_norm, axis=0))


# Print the average of the maximum value in each column of X_norm
np.mean(np.max(x_norm, axis=0))


1.7352202278916844

Be mindful that the exact values might not match since the dataset was initialized using the random function. 

# Data Spliting 

After data processing, it is a regular practice in ML to split the dataset into three datasets. 

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The ratios in which the data is split varies a bit from case to case. But the accepted standard 6:2:2 for train, test, and validation respectively. That is 60% for training data and so on. Again why is the data split or what is the signification of these smaller data sets? These questions are better left unanswered for now. 
The tanks assigned to you is to split the data in the given proportions randomly. 
For instance, if the data set had ten elements, this is how you would do it. 

In [11]:
# We create a random permutation of integers 0 to 9
np.random.permutation(10)

array([8, 3, 7, 5, 2, 6, 1, 9, 0, 4])

1. training set = 8,3,7,5,2,6
2. Cross Validation Set = 1,9
3. Test Set = 0,4

**Question 2.1** Similarly, create a 1D array representing the indexes of the rows in the dataset X_norm. U can use the   `np.random.permutation()` function for randomising the indexes. 

In [32]:
len(x_norm)

25000

In [35]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(len(x_norm))

In [36]:
# Print the shape of row_indices
row_indices.shape

(25000,)

**Question 2.2** Split the row indexes in the needed proportions. You can use the slicing methods you have learnt in this session to make the job easier.  

In [38]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
train = row_indices[:15000]
test = row_indices[15000:20000]
val  = row_indices[20000:]

**Question 2.3** Now make use of the indexes that you made to split the data also similarly once the data is split print the shape of each of the smaller data sets. `X_train` should have 15000 rows and 15 columns. `X_test` should have 5000 rows and 15 columns. `X_val` should have 5000 rows and 15 columns. 

In [40]:
# Create a Training Set
trainset = x_norm[train]
print(trainset.shape)

# Create a Cross Validation Set
valid = x_norm[val]
print(valid.shape)

# Create a Test Set
test = x_norm[test]
print(test.shape)


(15000, 15)
(5000, 15)
(5000, 15)


In [19]:
# Print the shape of X_train


# Print the shape of X_crossVal


# Print the shape of X_test


(15000, 15)
(5000, 15)
(5000, 15)
