In [1]:
import numpy as np

In [17]:
a1 = np.arange(1,5)
a2 = np.arange(5,9)
a1, a2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [18]:
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.stack((a1,a2), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.stack((a1,a2,a2), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [15]:
np.stack((a1,a2), axis=1)

array([[1, 1],
       [2, 3],
       [3, 3],
       [4, 2]])

In [9]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 1, 3, 3, 2])

In [10]:
np.vstack((a1,a2))

array([[1, 2, 3, 4],
       [1, 3, 3, 2]])

In [11]:
np.vstack((a1,a2)).shape

(2, 4)