In [1]:
import numpy as np

In [7]:
prices = np.array([25, 55, 55])
print(prices)
print(type(prices))

[25 55 55]
<class 'numpy.ndarray'>


In [18]:
prices_per_category = np.array([[2, 5, 5], [25, 7, 9]])
print(prices_per_category)
print(type(prices_per_category))

[[ 2  5  5]
 [25  7  9]]
<class 'numpy.ndarray'>


In [25]:
matrix = np.matrix([[2, 5, 5, 9], [5, 9, 9, 8]])
print(matrix)
print(type(matrix))

[[2 5 5 9]
 [5 9 9 8]]
<class 'numpy.matrix'>


In [27]:
print(prices_per_category.shape)
print(matrix.shape)
print(prices_per_category.ndim)
print(matrix.ndim)

(2, 3)
(2, 4)
2
2


In [28]:
print(matrix.dtype)
print(matrix.dtype)

int64
int64


In [37]:
tmp = np.array([False, 25, 55, 99, True])
print(tmp, type(tmp), tmp.dtype)

[ 0 25 55 99  1] <class 'numpy.ndarray'> int64


In [60]:
arr = np.arange(10, 70, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [61]:
arr.size

12

In [67]:
arr.reshape((6, 2))

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65]])

In [71]:
print(np.ones((5, 2)))
print(np.zeros((5, 2)))
print(np.random.random((5, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.19014327 0.82403992]
 [0.06787168 0.84975364]
 [0.66030943 0.22450189]
 [0.83405059 0.20839535]
 [0.94989727 0.14001316]]


In [76]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [77]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.arange(5, 2, -1)

array([5, 4, 3])

Exercise- create a 2d array of the given shape and range 25000 \* 15, with random integers from 0,10000


In [92]:
n = 5
m = 3
np.random.randint(0, 10000, (n, m))

array([[5988, 5258, 7089],
       [9708, 5386,   82],
       [8923, 9492, 3093],
       [8425, 6064, 7496],
       [8683, 2798, 5345]])

In [94]:
np.linspace(0, 10000, 5*3).reshape((n, m))

array([[    0.        ,   714.28571429,  1428.57142857],
       [ 2142.85714286,  2857.14285714,  3571.42857143],
       [ 4285.71428571,  5000.        ,  5714.28571429],
       [ 6428.57142857,  7142.85714286,  7857.14285714],
       [ 8571.42857143,  9285.71428571, 10000.        ]])

In [98]:
np.random.randint(5, 10, 50).reshape(2, 5, 5)

array([[[7, 8, 6, 8, 6],
        [5, 5, 8, 6, 5],
        [8, 9, 5, 5, 8],
        [6, 6, 9, 6, 6],
        [5, 9, 7, 9, 9]],

       [[8, 6, 8, 5, 8],
        [7, 9, 8, 9, 5],
        [8, 9, 9, 7, 6],
        [6, 8, 7, 6, 5],
        [7, 8, 8, 6, 6]]])