In [2]:
import numpy as np

In [3]:
prices = np.array([25, 55, 55])
print(prices)
print(type(prices))

[25 55 55]
<class 'numpy.ndarray'>


In [4]:
prices_per_category = np.array([[2, 5, 5], [25, 7, 9]])
print(prices_per_category)
print(type(prices_per_category))

[[ 2  5  5]
 [25  7  9]]
<class 'numpy.ndarray'>


In [5]:
matrix = np.matrix([[2, 5, 5, 9], [5, 9, 9, 8]])
print(matrix)
print(type(matrix))

[[2 5 5 9]
 [5 9 9 8]]
<class 'numpy.matrix'>


In [6]:
print(prices_per_category.shape)
print(matrix.shape)
print(prices_per_category.ndim)
print(matrix.ndim)

(2, 3)
(2, 4)
2
2


In [7]:
print(matrix.dtype)
print(matrix.dtype)

int64
int64


In [8]:
tmp = np.array([False, 25, 55, 99, True])
print(tmp, type(tmp), tmp.dtype)

[ 0 25 55 99  1] <class 'numpy.ndarray'> int64


In [9]:
arr = np.arange(10, 70, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [10]:
arr.size

12

In [11]:
arr.reshape((6, 2))

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65]])

In [12]:
np.random.randint(2,100)

58

In [13]:
print(np.ones((5, 2)))
print(np.zeros((5, 2)))
print(np.random.random((5, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.22742944 0.9528289 ]
 [0.97818738 0.85248314]
 [0.59638861 0.57369704]
 [0.71352341 0.30462327]
 [0.81956811 0.70722184]]


In [14]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(5, 2, -1)

array([5, 4, 3])

Exercise- create a 2d array of the given shape and range 25000 \* 15, with random integers from 0,10000


In [18]:
n = 5
m = 3
np.random.randint(0, 10000, (n, m))

array([[7599, 6758, 8263],
       [1436, 2787, 5778],
       [7744, 9268, 1455],
       [5312, 2040,  396],
       [6129,  807, 8723]])

In [19]:
np.linspace(0, 10000, 5*3).reshape((n, m))

array([[    0.        ,   714.28571429,  1428.57142857],
       [ 2142.85714286,  2857.14285714,  3571.42857143],
       [ 4285.71428571,  5000.        ,  5714.28571429],
       [ 6428.57142857,  7142.85714286,  7857.14285714],
       [ 8571.42857143,  9285.71428571, 10000.        ]])

In [20]:
np.random.randint(5, 10, 50).reshape(2, 5, 5)

array([[[7, 7, 5, 7, 5],
        [6, 5, 7, 6, 8],
        [9, 6, 6, 6, 9],
        [8, 9, 5, 6, 8],
        [9, 6, 8, 8, 9]],

       [[5, 9, 5, 6, 6],
        [6, 5, 7, 8, 7],
        [9, 6, 9, 7, 7],
        [8, 7, 5, 8, 8],
        [7, 5, 7, 8, 5]]])

In [25]:
np.random.randint(2,10, (3,5))

array([[3, 6, 6, 8, 4],
       [3, 4, 4, 7, 2],
       [3, 6, 2, 8, 8]])

In [27]:
np.random.random((2,3))

array([[0.1990926 , 0.12253445, 0.07180397],
       [0.06581252, 0.77773827, 0.12048737]])

In [40]:
a = np.arange(2,10,2)
b = np.arange(1,5)
c = np.arange(3,7)
a,b,c

(array([2, 4, 6, 8]), array([1, 2, 3, 4]), array([3, 4, 5, 6]))

In [43]:
np.hstack((a,b,c))

array([2, 4, 6, 8, 1, 2, 3, 4, 3, 4, 5, 6])

In [42]:
np.vstack((a,b,c)), np.vstack((a,b,c)).shape

(array([[2, 4, 6, 8],
        [1, 2, 3, 4],
        [3, 4, 5, 6]]),
 (3, 4))

In [41]:
np.column_stack((a,b,c))

array([[2, 1, 3],
       [4, 2, 4],
       [6, 3, 5],
       [8, 4, 6]])

In [46]:
np.tile(a, 2)

array([2, 4, 6, 8, 2, 4, 6, 8])

In [51]:
g1 = np.random.randint(1, 10, (3, 3))
g2 = np.random.randint(1, 10, (3, 2))
g3 = np.random.randint(1, 10, (2, 3))
g1, g2

(array([[3, 6, 5],
        [3, 4, 6],
        [2, 7, 9]]),
 array([[6, 2],
        [4, 5],
        [3, 4]]))

In [57]:
np.transpose(g1), np.transpose(g2)

(array([[3, 3, 2],
        [6, 4, 7],
        [5, 6, 9]]),
 array([[6, 4, 3],
        [2, 5, 4]]))

In [52]:
g1.transpose(), g2.transpose()

(array([[3, 3, 2],
        [6, 4, 7],
        [5, 6, 9]]),
 array([[6, 4, 3],
        [2, 5, 4]]))

In [53]:
np.dot(g1,g2)

array([[57, 56],
       [52, 50],
       [67, 75]])

In [55]:
np.dot(g1, g3)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [56]:
np.dot(g1, np.transpose(g3))

array([[ 28,  85],
       [ 28,  76],
       [ 33, 106]])

In [59]:
v1 = np.array([1, 2, 3, 4])
v1_ = np.array([1, 2, 3, 4])
v2 = np.array([[1], [2], [3], [4]])
v1.shape, v2.shape

((4,), (4, 1))

In [61]:
v1 + v1_, v1 + v2

(array([2, 4, 6, 8]),
 array([[2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7],
        [5, 6, 7, 8]]))